import mongoose from "mongoose";
import Manhwa from "./models/manhwa";

async function connectToDatabase() {
  try {
    await mongoose.connect("TEST_URI", {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log("Connexion à la base de données établie !");
  } catch (error) {
    console.error("Erreur de connexion à la base de données :", error);
  }
}

connectToDatabase();

async function seedDatabase() {
  try {
    await Manhwa.deleteMany(); // Supprime les données existantes
    await Manhwa.insertMany(manhwas); // Insère les nouvelles données
    console.log("Données insérées avec succès !");
  } catch (error) {
    console.error("Erreur lors de l'insertion des données :", error);
  } finally {
    mongoose.disconnect(); // Déconnectez-vous de la base de données après l'insertion
  }
}

seedDatabase();

const manhwas = [
  {
    title: "Sword Fanatic Wanders Through The Night",
    synopsis: `The Mystic Lunar Dance Troupe took in Jin Sohan as an orphan, and he spent his childhood with them.

    But one day, one of the four great demons, the Venom Demon, discovered that he was special and kidnapped him.
    
    After all kinds of test, he decided to raise him as his disciple.
    
    Ten years later, Jin Sohan tried to look for traces of the Mystic Lunar Dance Troupe, but the Sword Dance Troupe had already been destroyed at the hands of the Unorthodox Faction that’s now ruling over his hometown.`,
    author: "JP ,  YU Jin Sung et  Song Min (artiste)",
    genre: ["Action", "Adventure ", "Murim", "Martial Arts", "Fantasy"],
    cover:
      "https://asura.gg/wp-content/uploads/2022/06/swordfanaticCover01.png",
    chapters: [
      "https://asura.gg/wp-content/uploads/2022/06/01-kopya-15.jpg",
      "https://asura.gg/wp-content/uploads/2022/06/01-74.jpg",
      "https://asura.gg/wp-content/uploads/2022/06/01-copy-15.jpg",
      "https://asura.gg/wp-content/uploads/2022/06/01-75.jpg",
      "https://asura.gg/wp-content/uploads/2022/06/01-copy-17.jpg",
      "https://asura.gg/wp-content/uploads/2022/06/01-copy-16.jpg",
      "https://asura.gg/wp-content/uploads/2022/06/01-153.jpg",
      "https://asura.gg/wp-content/uploads/2022/06/01-227.jpg",
      "https://asura.gg/wp-content/uploads/2022/06/01-322.jpg",
      "https://asura.gg/wp-content/uploads/2022/07/01-copy-5.jpg",
      "https://asura.gg/wp-content/uploads/2022/07/01-69.jpg",
      "https://asura.gg/wp-content/uploads/2022/07/01-143.jpg",
      "https://asura.gg/wp-content/uploads/2022/07/01-222.jpg",
      "https://asura.gg/wp-content/uploads/2022/07/01-319.jpg",
      "https://asura.gg/wp-content/uploads/2022/08/01-copy-4.jpg",
      "https://asura.gg/wp-content/uploads/2022/08/sfw6-1.jpg",
      "https://asura.gg/wp-content/uploads/2022/08/sfw7-1.jpg",
      "https://asura.gg/wp-content/uploads/2022/08/01-82.jpg",
      "https://asura.gg/wp-content/uploads/2022/08/001-10.jpg",
      "https://asura.gg/wp-content/uploads/2022/08/01-187.jpg",
      "https://asura.gg/wp-content/uploads/2022/09/001-2.jpg",
      "https://asura.gg/wp-content/uploads/2022/09/01-134.jpg",
      "https://asura.gg/wp-content/uploads/2022/09/01-136.jpg",
      "https://asura.gg/wp-content/uploads/2022/09/01-214.jpg",
      "https://asura.gg/wp-content/uploads/2022/09/01-290.jpg",
      "https://asura.gg/wp-content/uploads/2022/10/01-93.jpg",
      "https://asura.gg/wp-content/uploads/2022/10/001.jpg",
      "https://asura.gg/wp-content/uploads/2022/10/01-271.jpg",
      "https://asura.gg/wp-content/uploads/2022/10/01-272.jpg",
      "https://asura.gg/wp-content/uploads/2022/10/01-274.jpg",
      "https://asura.gg/wp-content/uploads/2022/10/01-365.jpg",
      "https://asura.gg/wp-content/uploads/2022/11/01-13.jpg",
      "https://asura.gg/wp-content/uploads/2022/11/01-105.jpg",
      "https://asura.gg/wp-content/uploads/2022/11/01-190.jpg",
      "https://asura.gg/wp-content/uploads/2022/11/01-291.jpg",
      "https://asura.gg/wp-content/uploads/2022/11/01-361.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/01-89.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/01-229.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/01-336.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/0001-8.jpg",
      "https://asura.gg/wp-content/uploads/2023/01/01-40.jpg",
      "https://asura.gg/wp-content/uploads/2023/01/01-99.jpg",
      "https://asura.gg/wp-content/uploads/2023/01/01-163.jpg",
      "https://asura.gg/wp-content/uploads/2023/01/01-235.jpg",
    ],
    rating: 8,
    status: "Ongoing",
    comments: [
      { user: { pseudo: "Utilisateur 1", id: "ID 1" }, text: "Commentaire 1" },
      { user: { pseudo: "Utilisateur 2", id: "ID 2" }, text: "Commentaire 2" },
    ],
  },
  {
    title: "Return of the Disaster-Class Hero",
    synopsis: `I was the greatest hero on Earth.\n\n“But he’s dead. How could the guy we’ve killed come back?”\n\n“I dunno. But if he can come back, just let him.”\n\nI really came back after 20 years?\n\n“Why’re you so surprised? What? Did you do something to hurt your conscience?”\n\nYou bastards. Just you wait."`,
    author: "SAN.G (산지직송)",
    genre: ["Action", "Adventure ", "Magic", "Returner", "Fantasy"],
    cover:
      "https://asura.gg/wp-content/uploads/2021/10/DisasterheroCover02-1.png",
    chapters: [
      "https://asura.gg/wp-content/uploads/2021/12/01-303.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-244.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-290.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-247.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-292.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-293.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-405.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-406.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-297.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-407.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-408.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-322.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-259.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-323.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-324.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-325.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-327.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-328.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-gigapixel-standard-width-800px.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-329.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-355.jpg",
      "https://asura.gg/wp-content/uploads/2022/01/01-41.jpg",
      "https://asura.gg/wp-content/uploads/2022/01/01-79.jpg",
      "https://asura.gg/wp-content/uploads/2022/01/01-kopya-13.jpg  ",
      "https://asura.gg/wp-content/uploads/2022/01/01-175.jpg",
      "https://asura.gg/wp-content/uploads/2022/02/01-17.jpg",
      "https://asura.gg/wp-content/uploads/2022/02/01-58.jpg",
      "https://asura.gg/wp-content/uploads/2022/02/01-123.jpg",
      "https://asura.gg/wp-content/uploads/2022/02/01-165.jpg",
      "https://asura.gg/wp-content/uploads/2022/03/01-kopya.jpg",
      "https://asura.gg/wp-content/uploads/2022/03/01-kopya-9.jpg",
      "https://asura.gg/wp-content/uploads/2022/03/01-kopya-23.jpg",
    ],
    rating: 9.5,
    status: "Ongoing",
    comments: [
      { user: { pseudo: "Utilisateur 1", id: "ID 1" }, text: "Commentaire 1" },
      { user: { pseudo: "Utilisateur 2", id: "ID 2" }, text: "Commentaire 2" },
    ],
  },
  {
    title: "Infinite Mage",
    synopsis: `Abandoned at birth in a stable, Shirone was raised by commoners.

    As a child, he had gifted Insight and had learned how to read. After visiting the city, he finally saw the workings of magic, which he was immensely curious about.
    
    This inspired Shirone’s dream of becoming a mage. However, the city was a place with a cruel and rigid social hierarchy. Here, Shirone discovered the hidden side of the world before he even reached adulthood…
    
    Will Shirone be able to achieve his dream of becoming a mage in this twisted world?
    
    `,
    author: "Kim Chiwoo/kiraz",
    genre: [
      "Action",
      "Adventure",
      "Drama",
      "Fantasy",
      "Genius MC",
      "Supernatural",
    ],
    cover:
      "https://asura.gg/wp-content/uploads/2022/12/infiniteMageCover01.png",
    chapters: [
      "https://asura.gg/wp-content/uploads/2022/12/01-628.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/01-629.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/01-630.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/01-kopya-16.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/01-copy-37.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/01-631.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/01-633.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/01-632.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/01-634.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/01-635.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/01-copy-38.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/01-636.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/IM13-2.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/IM14-2.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/IM15-2.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/IM16-2.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/IM17-1.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/IM18-2.jpg",
      "https://asura.gg/wp-content/uploads/2023/01/01-30.jpg",
      "https://asura.gg/wp-content/uploads/2023/01/01-85.jpg",
      "https://asura.gg/wp-content/uploads/2023/01/01-copy-17.jpg",
      "https://asura.gg/wp-content/uploads/2023/01/01-copy-22.jpg",
      "https://asura.gg/wp-content/uploads/2023/02/01-55.jpg",
      "https://asura.gg/wp-content/uploads/2023/02/01-copy-7.jpg",
      "https://asura.gg/wp-content/uploads/2023/02/01-copy-14.jpg",
      "https://asura.gg/wp-content/uploads/2023/03/01-13.jpg",
      "https://asura.gg/wp-content/uploads/2023/03/01-copy-7.jpg",
    ],
    rating: 9.9,
    status: "Ongoing",
    comments: [
      { user: { pseudo: "Utilisateur 1", id: "ID 1" }, text: "Commentaire 1" },
      { user: { pseudo: "Utilisateur 2", id: "ID 2" }, text: "Commentaire 2" },
    ],
  },
  {
    title: "Pick Me Up, Infinite Gacha",
    synopsis: `The mobile gacha game ‘Pick Me Up!’ is known for being brutally difficult, and no one has been able to clear a dungeon. Loki, the fifth among all the world’s masters, loses consciousness while trying to clear the dungeon. Upon waking up, Loki finds himself turned into a 1-star level 1 hero, ‘Islat Han’. “It’s him! I’m certain he’s the one who brought me here!” In order to return to Earth, he must lead novice masters and heroes and break through the 100th floor of the dungeon! “You messed with the wrong person.” This is the story of master Loki who is forced to carry everyone to victory and cannot afford a single defeat.`,
    author: "Hermode/Cho Wooneh",
    genre: ["Action", "Adventure", "Comedy", "Fantasy", "System"],
    cover:
      "https://asura.gg/wp-content/uploads/2022/12/infiniteGachaCover03.png",
    chapters: [
      "https://asura.gg/wp-content/uploads/2022/12/01-583.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/01-584.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/01-585.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/0001-9.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/01-586.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/01-kopya-14.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/001-4.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/01-587.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/001-5.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/01-kopya-15.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/0001-10.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/001-6.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/001-7.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/0001-11.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/01-588.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/01-589.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/01-591.jpg",
      "https://asura.gg/wp-content/uploads/2022/12/01-592.jpg",
    ],
    rating: 9.9,
    status: "Ongoing",
    comments: [
      { user: { pseudo: "Utilisateur 1", id: "ID 1" }, text: "Commentaire 1" },
      { user: { pseudo: "Utilisateur 2", id: "ID 2" }, text: "Commentaire 2" },
    ],
  },
  {
    title: "Terminally-Ill Genius Dark Knight",
    synopsis: `However, to Yoo Chan, who was diagnosed with a terminal illness at a young age, this game was his entire life and has now become his reality.
    From now on, Yoo Chan has to survive in this world as Nox von Reinharber, the worst villain in the first act of the game. Will he be able to reach the end of the story safely?`,
    author: "Jung SeonYul , Nagi(artist) ",
    genre: ["Action", "Adventure", "Fantasy", "Game", "Psychological"],
    cover:
      "https://asura.gg/wp-content/uploads/2023/05/terminallyilldarkknightCover01.png",
    chapters: [
      "https://asura.gg/wp-content/uploads/2023/05/0n001-2.jpg",
      "https://asura.gg/wp-content/uploads/2023/05/01-kopya-6.jpg",
      "https://asura.gg/wp-content/uploads/2023/05/01-91.jpg",
      "https://asura.gg/wp-content/uploads/2023/05/01-92.jpg",
      "https://asura.gg/wp-content/uploads/2023/05/01-kopya-8.jpg",
      "https://asura.gg/wp-content/uploads/2023/05/01-kopya-7.jpg",
      "https://asura.gg/wp-content/uploads/2023/05/SS-001.jpg",
      "https://asura.gg/wp-content/uploads/2023/05/TIGK-001.jpg",
      "https://asura.gg/wp-content/uploads/2023/05/TIGK-0001.jpg",
      "https://asura.gg/wp-content/uploads/2023/06/01-49.jpg",
      "https://asura.gg/wp-content/uploads/2023/06/01-kopya-4.jpg",
      "https://asura.gg/wp-content/uploads/2023/06/01-102.jpg",
      "https://asura.gg/wp-content/uploads/2023/06/01-176.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/IDKn-001.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01-137.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01-222.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01-copy-36.jpg",
      "https://asura.gg/wp-content/uploads/2023/08/01-copy-5.jpg",
      "https://asura.gg/wp-content/uploads/2023/08/01-copya.jpg",
    ],
    rating: 9.7,
    status: "Ongoing",
    comments: [
      { user: { pseudo: "Utilisateur 1", id: "ID 1" }, text: "Commentaire 1" },
      { user: { pseudo: "Utilisateur 2", id: "ID 2" }, text: "Commentaire 2" },
    ],
  },
  {
    title: "I Captured The Tyrant’s Heart",
    synopsis: `I am the sole friend of the Crown Prince, the Young Lady Euceniel Hardrant.
    One day, my family was chased out of the Capital all because I was considered a bad influence on the Crown Prince.
    After reuniting 14 years later, he had changed drastically. When I asked why he had changed, he said it was because that was the kind of appearance he felt I preferred of a Crown Prince, no, of the Emperor, Tesvalun Neusville.
    But it seems his appearance wasn’t the only thing that had changed.`,
    author: "Ari, Nobena (Artist)",
    genre: ["Adventure", "Fantasy", "Mature", "Romance", "Shujo"],
    cover: "https://asura.gg/wp-content/uploads/2023/07/F1PZWa5acAAPBRs.jpeg",
    chapters: [
      "https://asura.gg/wp-content/uploads/2023/07/01-kopya-14.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01-202.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01-203.jpg",
    ],
    rating: 6,
    status: "Dropped",
    comments: [
      { user: { pseudo: "Utilisateur 1", id: "ID 1" }, text: "Commentaire 1" },
      { user: { pseudo: "Utilisateur 2", id: "ID 2" }, text: "Commentaire 2" },
    ],
  },
  {
    title: "Solo Leveling Side Story",
    synopsis: `10 years ago, after “the Gate” that connected the real world with the monster world opened, some of the ordinary, everyday people received the power to hunt monsters within the Gate. They are known as “Hunters”. However, not all Hunters are powerful. My name is Sung Jin-Woo, an E-rank Hunter. I’m someone who has to risk his life in the lowliest of dungeons, the “World’s Weakest”. Having no skills whatsoever to display, I barely earned the required money by fighting in low-leveled dungeons… at least until I found a hidden dungeon with the hardest difficulty within the D-rank dungeons! In the end, as I was accepting death, I suddenly received a strange power, a quest log that only I could see, a secret to leveling up that only I know about! If I trained in accordance with my quests and hunted monsters, my level would rise. Changing from the weakest Hunter to the strongest S-rank Hunter!`,
    author: "추공 (Chugong), GEE So-Lyung (Artist)",
    genre: ["Action", "Adventure", "Fantasy", "Shounen"],
    cover:
      "https://asura.gg/wp-content/uploads/2021/03/soloLevelingCover02.png",
    chapters: [
      "https://asura.gg/wp-content/uploads/2023/01/01-189.jpg",
      "https://asura.gg/wp-content/uploads/2023/01/01-190.jpg",
      "https://asura.gg/wp-content/uploads/2023/01/01-253.jpg",
      "https://asura.gg/wp-content/uploads/2023/02/01-5.jpg",
      "https://asura.gg/wp-content/uploads/2023/02/01-63.jpg",
      "https://asura.gg/wp-content/uploads/2023/02/01-131.jpg",
      "https://asura.gg/wp-content/uploads/2023/02/01-225.jpg",
      "https://asura.gg/wp-content/uploads/2023/03/01.jpg",
      "https://asura.gg/wp-content/uploads/2023/03/01-90.jpg",
      "https://asura.gg/wp-content/uploads/2023/03/01-157.jpg",
      "https://asura.gg/wp-content/uploads/2023/03/01-247.jpg",
      "https://asura.gg/wp-content/uploads/2023/03/01-321.jpg",
      "https://asura.gg/wp-content/uploads/2023/04/01-70.jpg",
      "https://asura.gg/wp-content/uploads/2023/04/01-157.jpg",
      "https://asura.gg/wp-content/uploads/2023/04/01-259.jpg",
      "https://asura.gg/wp-content/uploads/2023/04/01-340.jpg",
      "https://asura.gg/wp-content/uploads/2023/05/01-44.jpg",
      "https://asura.gg/wp-content/uploads/2023/05/SL18-1.jpg",
      "https://asura.gg/wp-content/uploads/2023/05/Scar-001-4.jpg",
      "https://asura.gg/wp-content/uploads/2023/05/01-136.jpg",
      "https://asura.gg/wp-content/uploads/2023/05/SL-001.jpg",
      "https://asura.gg/wp-content/uploads/2023/05/SL-001.jpg",
    ],
    rating: 10,
    status: "Completed",
    comments: [
      { user: { pseudo: "Utilisateur 1", id: "ID 1" }, text: "Commentaire 1" },
      { user: { pseudo: "Utilisateur 2", id: "ID 2" }, text: "Commentaire 2" },
    ],
  },
  {
    title: "Dangerous Dungeon Escape",
    synopsis: `Go Insung did not pass onto hell or heaven after suddenly dying, but instead onto a dungeon. A place in between the afterlife and the world.
    And it’s no normal dungeon, but one with a system.
    While being watched by the numerous dead of the afterlife, Go Insung has to clear the dungeon with the other challengers in order to escape.`,
    author: "Anonymous Author",
    genre: ["Action", "Fantasy", "Dungeons", "System"],
    cover:
      "https://asura.gg/wp-content/uploads/2023/02/FoxKwQuaUAE4917CUnetauto_scaleLevel3width_1000.jpg",
    chapters: [
      "https://asura.gg/wp-content/uploads/2023/02/01-copy-5.jpg",
      "https://asura.gg/wp-content/uploads/2023/02/01-84.jpg",
      "https://asura.gg/wp-content/uploads/2023/02/01-83.jpg",
      "https://asura.gg/wp-content/uploads/2023/02/01-kopya-6.jpg",
      "https://asura.gg/wp-content/uploads/2023/02/01-85.jpg",
      "https://asura.gg/wp-content/uploads/2023/02/01-86.jpg",
      "https://asura.gg/wp-content/uploads/2023/02/01-87.jpg",
      "https://asura.gg/wp-content/uploads/2023/02/01-88.jpg",
      "https://asura.gg/wp-content/uploads/2023/02/01-kopya-7.jpg",
      "https://asura.gg/wp-content/uploads/2023/02/01-89.jpg",
      "https://asura.gg/wp-content/uploads/2023/02/01-90.jpg",
      "https://asura.gg/wp-content/uploads/2023/02/01-91.jpg",
      "https://asura.gg/wp-content/uploads/2023/02/01-copy-6.jpg",
      "https://asura.gg/wp-content/uploads/2023/02/01-196.jpg",
      "https://asura.gg/wp-content/uploads/2023/02/01-330.jpg",
      "https://asura.gg/wp-content/uploads/2023/03/notices.jpg",
    ],
    rating: 5,
    status: "Dropped",
    comments: [
      { user: { pseudo: "Utilisateur 1", id: "ID 1" }, text: "Commentaire 1" },
      { user: { pseudo: "Utilisateur 2", id: "ID 2" }, text: "Commentaire 2" },
    ],
  },
  {
    title: "Bones",
    synopsis: `The protagonist Jihyoung wanted to become a hunter for his mother. However, his bullies put his mother into a vegetative state. Jihyoung tried to take revenge, but was beaten down instead and buried alive… He becomes a beast and starts his hunt.`,
    author: "Igeon",
    genre: ["Action", "Adventure", "Fantasy", "Revenge"],
    cover:
      "https://asura.gg/wp-content/uploads/2023/07/replicate-prediction-qwsgkvjbphpiuzsgy7ysbddpum.png",
    chapters: [
      "https://asura.gg/wp-content/uploads/2023/07/1-upload_7161909988391281713.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/BO_001.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/0001-kopya.jpg",
    ],
    rating: 9,
    status: "Ongoing",
    comments: [
      { user: { pseudo: "Utilisateur 1", id: "ID 1" }, text: "Commentaire 1" },
      { user: { pseudo: "Utilisateur 2", id: "ID 2" }, text: "Commentaire 2" },
    ],
  },
  {
    title: "The Priest of Corruption",
    synopsis: `I used a cheat to create a character in the game. When I came to my senses after pressing the play button, I had possessed the “Priest of Corruption” character I had created. It had to be a character who had bad stats and was hated by all! All I had on me is a woman’s dried up hand, but that hand was a goddess’s?!`,
    author: "Sadadeum/ Barley, YU (artist)",
    genre: ["Action", "Adventure", "Fantasy", "Psychological"],
    cover:
      "https://asura.gg/wp-content/uploads/2023/06/ThePriestOfCorruptionCover02.png",
    chapters: [
      "https://asura.gg/wp-content/uploads/2023/06/PCC-001.jpg",
      "https://asura.gg/wp-content/uploads/2023/06/PCC2-001.jpg",
      "https://asura.gg/wp-content/uploads/2023/06/PCC3-001.jpg",
      "https://asura.gg/wp-content/uploads/2023/06/PC4-001.jpg",
      "https://asura.gg/wp-content/uploads/2023/06/PC5-001.jpg",
      "https://asura.gg/wp-content/uploads/2023/06/PC6-001.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01_1.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/PS_0001-1.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/9_1.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/10_0001.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01-208.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01-209.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/Priest-001.jpg",
      "https://asura.gg/wp-content/uploads/2023/08/PR_0001.jpg",
      "https://asura.gg/wp-content/uploads/2023/08/01-21.jpg",
      "https://asura.gg/wp-content/uploads/2023/08/01-22.jpg",
    ],
    rating: 8,
    status: "Ongoing",
    comments: [
      { user: { pseudo: "Utilisateur 1", id: "ID 1" }, text: "Commentaire 1" },
      { user: { pseudo: "Utilisateur 2", id: "ID 2" }, text: "Commentaire 2" },
    ],
  },
  {
    title: "Academy’s Genius Swordmaster",
    synopsis: `Ronan lived a wasteful life filled with regrets. A second chance befalls him at the end of his futile life. He went back to the time when he was a ten-year-old child! For the people who sacrificed themselves for him, he becomes determined to live a new life.`,
    author: "Anonymous Author",
    genre: ["Action", "Adventure", "Fantasy", "Genius MC", "Returner"],
    cover:
      "https://asura.gg/wp-content/uploads/2023/07/replicate-prediction-vl2hajjbgudda4cvzc7qwxj3iy.png",
    chapters: [
      "https://asura.gg/wp-content/uploads/2023/07/01-kopya-28.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/001-copy.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/GN_001.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01-kopya-29.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01-copy-46.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01-277.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01-278.jpg",
      "https://asura.gg/wp-content/uploads/2023/08/01-kopya-2.jpg",
    ],
    rating: 7.5,
    status: "Ongoing",
    comments: [
      { user: { pseudo: "Utilisateur 1", id: "ID 1" }, text: "Commentaire 1" },
      { user: { pseudo: "Utilisateur 2", id: "ID 2" }, text: "Commentaire 2" },
    ],
  },
  {
    title: "The Blood Knight’s Villains",
    synopsis: `“Dark World,” the game I, a thirty-year-old salaryman, had devoted my entire youth to. “What the fuck is this…” When I opened my eyes, Dark World had become my reality. The pouring rain, dripping hot blood, and a cold blade. At the moment of my impending death, I came into this familiar world.`,
    author: "파랑손 , Daon Studio (Artists Studio)",
    genre: ["Action", "Adventure", "Fantasy"],
    cover: "https://asura.gg/wp-content/uploads/2023/07/000cover_2.png",
    chapters: [
      "https://asura.gg/wp-content/uploads/2023/07/01-kopya-25.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01-copy-37.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/BL_001.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01-270.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01-271.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01-copy-38.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01-272.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/SR-002.jpg",
    ],
    rating: 8,
    status: "Ongoing",
    comments: [
      { user: { pseudo: "Utilisateur 1", id: "ID 1" }, text: "Commentaire 1" },
      { user: { pseudo: "Utilisateur 2", id: "ID 2" }, text: "Commentaire 2" },
    ],
  },
  {
    title: "Demonic Spirit King",
    synopsis: `In a world where the murim world of the past continued onto the present…
    After the killer ‘Demonic Spirit King’ vanished into thin air, the murim world was at peace.
    However, one day, a drug that increases the internal energy of the people of murim appears and disrupts the balance of power.
    Just in time, the ‘Demonic Spirit King’ shows himself to the world once again,
    And throws the world of murim into a vortex of chaos once again…`,
    author: "Son Go-hoo, Park Jin-Seok(artist)",
    genre: ["Action", "Fantasy", "Martials Arts"],
    cover: "https://asura.gg/wp-content/uploads/2021/11/DemonicSpiritKing.jpg",
    chapters: [
      "https://asura.gg/wp-content/uploads/2021/11/01-81.jpg",
      "https://asura.gg/wp-content/uploads/2021/11/01-82.jpg",
      "https://asura.gg/wp-content/uploads/2021/11/01-83.jpg",
      "https://asura.gg/wp-content/uploads/2021/11/01-95.jpg",
      "https://asura.gg/wp-content/uploads/2021/11/01-96.jpg",
      "https://asura.gg/wp-content/uploads/2021/11/01-97.jpg",
      "https://asura.gg/wp-content/uploads/2021/11/01-108.jpg",
      "https://asura.gg/wp-content/uploads/2021/11/01-99.jpg",
      "https://asura.gg/wp-content/uploads/2021/11/01-100.jpg",
      "https://asura.gg/wp-content/uploads/2021/11/01-101.jpg",
      "https://asura.gg/wp-content/uploads/2021/11/01-109.jpg",
      "https://asura.gg/wp-content/uploads/2021/11/01-103.jpg",
      "https://asura.gg/wp-content/uploads/2021/11/01-104.jpg",
      "https://asura.gg/wp-content/uploads/2021/11/01-105.jpg",
      "https://asura.gg/wp-content/uploads/2021/11/01-263.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-27.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-123.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-216.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-286.jpg",
      "https://asura.gg/wp-content/uploads/2021/12/01-368.jpg",
      "https://asura.gg/wp-content/uploads/2022/01/01-46.jpg",
      "https://asura.gg/wp-content/uploads/2022/01/01-119.jpg",
      "https://asura.gg/wp-content/uploads/2022/01/01-155.jpg",
      "https://asura.gg/wp-content/uploads/2022/01/01-197.jpg",
      "https://asura.gg/wp-content/uploads/2022/02/page1-1.jpg",
      "https://asura.gg/wp-content/uploads/2022/02/01-76.jpg",
      "https://asura.gg/wp-content/uploads/2022/02/page1-8.jpg",
      "https://asura.gg/wp-content/uploads/2022/02/01-196.jpg",
      "https://asura.gg/wp-content/uploads/2022/03/0001-6.jpg",
      "https://asura.gg/wp-content/uploads/2022/03/01-95.jpg",
      "https://asura.gg/wp-content/uploads/2022/03/01-224.jpg",
      "https://asura.gg/wp-content/uploads/2022/03/01-249.jpg",
      "https://asura.gg/wp-content/uploads/2022/03/01-301.jpg",
      "https://asura.gg/wp-content/uploads/2022/04/01-104.jpg",
      "https://asura.gg/wp-content/uploads/2022/04/01-234.jpg",
    ],
    rating: 4.5,
    status: "Dropped",
    comments: [
      { user: { pseudo: "Utilisateur 1", id: "ID 1" }, text: "Commentaire 1" },
      { user: { pseudo: "Utilisateur 2", id: "ID 2" }, text: "Commentaire 2" },
    ],
  },
  {
    title: "Martial God Regressed to Level 2",
    synopsis: `“Battle Net,” which was thought to be a game, turned into a disaster for humankind. After the “Space League” was hosted, all living organisms in the universe fought for their lives. Humanity, represented by Earth, kept failing and was eventually annihilated. Except for one person, “Martial Saint” Seong Jihan. His skill, “Nameless Divine Arts,” resisted the system’s deletion. Humanity, which had been deemed worthless, received another “chance.” This was the second chance granted to Seong Jihan. “Things will be different this time.” Since he, the one who completed the game, had returned.`,
    author: "Ah Nyunsung (D&C Webtoon Biz) / Yeombi, Ah Yoongu (Artist)",
    genre: [
      "Action",
      "Fantasy",
      "Martials Arts",
      "Overpowered",
      "Regression",
      "Reincarnation",
    ],
    cover:
      "https://asura.gg/wp-content/uploads/2023/07/replicate-prediction-racly3rbhmzlnnex2krwvuaada.png",
    chapters: [
      "https://asura.gg/wp-content/uploads/2023/07/New-001.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/GM_0001.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/MG_001.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/MGG_0001.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/ML_-kopya001.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/MLG_001.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/GT_001.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/MGT_-copy001.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/New9-001.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/GR_0001.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/New11-001.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01-copy-48.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01-280.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01-kopya-34.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01-281.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01-kopya-32.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01-copy-49.jpg",
    ],
    rating: 8.7,
    status: "Ongoing",
    comments: [
      { user: { pseudo: "Utilisateur 1", id: "ID 1" }, text: "Commentaire 1" },
      { user: { pseudo: "Utilisateur 2", id: "ID 2" }, text: "Commentaire 2" },
    ],
  },
  {
    title: "For My Forsaken Beloved",
    synopsis: `“Save my dearest love!” Hestia, who loved the incomplete romantic fantasy novel enough to isekai, was insignificant, even among the extras who got possessed.
    Finally, the novel has come to its end with her watching the main characters in person! The conclusion of the novel left her thinking that she’d return to her world, but that thought turned to ashes. She was shocked when she found out about the novel’s behind-the-scenes ending that showed the death of her beloved, the sub male lead Caelus. Without even taking a break, she regresses…! ‘This time, I will protect my beloved!`,
    author: "Anonymous Author",
    genre: ["Drama", "Fantasy", "Returner", "Romance"],
    cover: "https://asura.gg/wp-content/uploads/2022/05/unknown-4.png",
    chapters: [
      "https://asura.gg/wp-content/uploads/2022/05/01-181.jpg",
      "https://asura.gg/wp-content/uploads/2022/05/01-198.jpg",
      "https://asura.gg/wp-content/uploads/2022/05/01-211.jpg",
      "https://asura.gg/wp-content/uploads/2022/05/01-229.jpg",
      "https://asura.gg/wp-content/uploads/2022/05/01-230.jpg",
      "https://asura.gg/wp-content/uploads/2022/05/01-239.jpg",
      "https://asura.gg/wp-content/uploads/2022/05/01-240.jpg",
      "https://asura.gg/wp-content/uploads/2022/05/01-251.jpg",
      "https://asura.gg/wp-content/uploads/2022/06/01-7.jpg",
    ],
    rating: 8,
    status: "Dropped",
    comments: [
      { user: { pseudo: "Utilisateur 1", id: "ID 1" }, text: "Commentaire 1" },
      { user: { pseudo: "Utilisateur 2", id: "ID 2" }, text: "Commentaire 2" },
    ],
  },
  {
    title: "Chronicles of the Demon Faction",
    synopsis: `Chun Hajin, the strongest assassin of the Orthodox Murim’s Righteous Heavenly Alliance. Hajin loses his life as he tries to escape to find freedom.
    And then…
    ‘The divine cult is immortal, may all demons submit. Congratulations on your recovery, third young master!’
    He was reincarnated into the body of Murim’s public enemy, the third young master of the Demonic Cult?!
    The conquest of the Demonic Murim by Chun Hajin, the strongest secret weapon of the Orthodox Murim, begins now.`,
    author: "codezero",
    genre: ["Action", "Adventure", "Demon", "Murim"],
    cover:
      "https://asura.gg/wp-content/uploads/2023/03/DemonFactionCover02.png",
    chapters: [
      "https://asura.gg/wp-content/uploads/2023/03/01-273.jpg",
      "https://asura.gg/wp-content/uploads/2023/03/01-274.jpg",
      "https://asura.gg/wp-content/uploads/2023/03/01-278.jpg",
      "https://asura.gg/wp-content/uploads/2023/03/01-279.jpg",
      "https://asura.gg/wp-content/uploads/2023/03/01-301.jpg",
      "https://asura.gg/wp-content/uploads/2023/03/01-302.jpg",
      "https://asura.gg/wp-content/uploads/2023/03/01-303.jpg",
      "https://asura.gg/wp-content/uploads/2023/04/01-57.jpg",
      "https://asura.gg/wp-content/uploads/2023/04/01-131.jpg",
      "https://asura.gg/wp-content/uploads/2023/04/01-253.jpg",
      "https://asura.gg/wp-content/uploads/2023/04/01-368.jpg",
      "https://asura.gg/wp-content/uploads/2023/05/01-24.jpg",
      "https://asura.gg/wp-content/uploads/2023/05/01-47.jpg",
      "https://asura.gg/wp-content/uploads/2023/05/CODF14-1.jpg",
      "https://asura.gg/wp-content/uploads/2023/05/01-123.jpg",
      "https://asura.gg/wp-content/uploads/2023/05/01-124.jpg",
      "https://asura.gg/wp-content/uploads/2023/06/01.jpg",
      "https://asura.gg/wp-content/uploads/2023/06/01-32.jpg",
      "https://asura.gg/wp-content/uploads/2023/06/01-33.jpg",
      "https://asura.gg/wp-content/uploads/2023/06/DF_001.jpg",
      "https://asura.gg/wp-content/uploads/2023/06/017-0001.jpg",
      "https://asura.gg/wp-content/uploads/2023/06/01-191.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01-51.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/01-146.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/25_1.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/CODF26-2.jpg",
      "https://asura.gg/wp-content/uploads/2023/07/CODF27-2.jpg",
      "https://asura.gg/wp-content/uploads/2023/08/CODF28-2.jpg",
    ],
    rating: 9.3,
    status: "Ongoing",
    comments: [
      { user: { pseudo: "Utilisateur 1", id: "ID 1" }, text: "Commentaire 1" },
      { user: { pseudo: "Utilisateur 2", id: "ID 2" }, text: "Commentaire 2" },
    ],
  },
  {
    title: "Titre du manhwa 1",
    synopsis: "Synopsis du manhwa 1",
    author: "Auteur 1",
    genre: ["Genre 1", "Genre 2"],
    cover: "lien_vers_l_image_1",
    chapters: ["Chapitre 1", "Chapitre 2"],
    rating: 4.5,
    status: "Ongoing",
    comments: [
      { user: { pseudo: "Utilisateur 1", id: "ID 1" }, text: "Commentaire 1" },
      { user: { pseudo: "Utilisateur 2", id: "ID 2" }, text: "Commentaire 2" },
    ],
  },
  {
    title: "Titre du manhwa 1",
    synopsis: "Synopsis du manhwa 1",
    author: "Auteur 1",
    genre: ["Genre 1", "Genre 2"],
    cover: "lien_vers_l_image_1",
    chapters: ["Chapitre 1", "Chapitre 2"],
    rating: 4.5,
    status: "Ongoing",
    comments: [
      { user: { pseudo: "Utilisateur 1", id: "ID 1" }, text: "Commentaire 1" },
      { user: { pseudo: "Utilisateur 2", id: "ID 2" }, text: "Commentaire 2" },
    ],
  },
  {
    title: "Titre du manhwa 1",
    synopsis: "Synopsis du manhwa 1",
    author: "Auteur 1",
    genre: ["Genre 1", "Genre 2"],
    cover: "lien_vers_l_image_1",
    chapters: ["Chapitre 1", "Chapitre 2"],
    rating: 4.5,
    status: "Ongoing",
    comments: [
      { user: { pseudo: "Utilisateur 1", id: "ID 1" }, text: "Commentaire 1" },
      { user: { pseudo: "Utilisateur 2", id: "ID 2" }, text: "Commentaire 2" },
    ],
  },
];
