name: "CI"

on:
  pull_request:
    branches: ["master"]

jobs:
  test-back:
    runs-on: ubuntu-latest
    env:
      TEST_URI: ${{ secrets.TEST_URI }}
      ENV: "test"
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2 

    - name: Start test environment
      run: docker compose -f ./docker-compose.test.yml up -d --build --force-recreate --quiet-pull

    - name: Wait for tests to finish
      run: |
        while true; do
          sleep 2
          if ! docker ps -q --filter "status=running" --filter "name=ci-testing-test-api-1" >/dev/null; then
            echo "Test Done!"
            break
          fi
        done

    - name: Display and analyse test results
      run: |
        result=$(docker logs ci-testing-test-api-1)
        echo "$result"
        if [[ "$result" == *"failing"* ]]; then
          echo "Tests have failed :/"
          exit 1
        else
          echo "All tests passed :)"
          exit 0
        fi